### ISSUE TITLE
Retry mechanism for failed push [$15 awarded]

### ISSUE THREAD

**Issue by vtemian** [PressLabs/gitfs#201]
If the push failed because some changes from remote were not fetched, we should try to fetch, merge them and in the end, retry the push.

**Comment by krodyrobi** [comment]
Sample log Jan 27 15:38:04 sftp-5 GitFS:  on /home/dragosroua/connecthubro [12571]: SyncWorker: Push failed Traceback (most recent call last):   File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/worker/sync.py", line 122, in sync     self.repository.push(self.upstream, self.branch)   File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/repository.py", line 119, in push     remote.push(["refs/heads/%s" % (branch)])   File "/root/.pex/install/pygit2-0.22.0-cp27-none-linux_x86_64.whl.6071446922e1dec09888986ed337431aa6163780/pygit2-0.22.0-cp27-none-linux_x86_64.whl/pygit2/remote.py", line 322, in push     check_error(err)   File "/root/.pex/install/pygit2-0.22.0-cp27-none-linux_x86_64.whl.6071446922e1dec09888986ed337431aa6163780/pygit2-0.22.0-cp27-none-linux_x86_64.whl/pygit2/errors.py", line 64, in check_error     raise GitError(message) GitError: Cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.
