### ISSUE TITLE
Files only being fetched/pulled sporadically

### ISSUE THREAD

**Issue by markTward** [PressLabs/gitfs#205]
First time attempting to use gitfs.  My use case is for small group of services which share common and rarely changing data files.

From the doc, my expectation was that commits would be automatically pulled/merged onto the local gitfs mount point at the interval defined with option fetch_delay.  Is this the expected behavior?

From observing the gitfs logging in syslog in debug mode, what I'm finding is that the FetchWorker isn't firing at regular intervals.  However, if I make a local change, it is quickly pushed up and then any upstream changes are pulled.

Looking forward to understanding how to use gitfs in the real world.

Cheers,
Mark

gitfs --version
GitFS 0.3.3

git --version
git version 1.9.1

**Comment by vtemian** [comment]
Hi @markTward,

The correct parameter is `fetch_timeout`, not `fetch_delay`. We fixed the documentation as well. (https://www.presslabs.com/gitfs/docs/arguments/#)

The default `fetch_timeout` is `30s` and maybe that's why you didn't saw any logs.

Can you try to remount it again and see if this solved the problem?
