### ISSUE TITLE
gitfs hangs while doing a large push to the repository

### ISSUE THREAD

**Issue by eddienko** [PressLabs/gitfs#233]
I am testing gitfs as a file version filesystem of binary files. I have done a test copying ~1GB binary files to the mount directory. gitfs does the commit and pushes to the repository synchronously. This means that while it is pushing to the repository the system does not allow additional writes to the mount path until the push is finished.

```
June-04-2016 08:37:15 SyncWorker: Get some commits
June-04-2016 10:09:34 SyncWorker: Push done
```

In this example, it is not possible to write to the mount point between 'Get some commits' and 'Push done'.

Ideally the push should be done asynchronously so that further writes can be carried out.

**Comment by vtemian** [comment]
Hi @eddienko,

Sorry for the late reply. This behavior was chosen in order to be as POSIX complaint as possible.
If the push is done asynchronously, then you'll risk to have inconsistent writes (a push may fail, but you continue to change the state of the repository).

Now, Gitfs will delay any write operation until a push is done. If the push fails, the entire file system will move to read-only, until the push is done (since 0.4.0, Gitfs have a retry mechanism).

I know that is suitable for large binary files, but implementing https://github.com/PressLabs/gitfs/issues/203 should improve the behaviour.

Thank you for trying Gitfs and if you have any question, don't hesitate to ask.
